CREATE TABLE IF NOT EXISTS Server (
	id INTEGER NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	port INTEGER NOT NULL,
	client_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Message (
	id INTEGER NOT NULL PRIMARY KEY,
	fk_server_id INTEGER NOT NULL,
	topic TEXT NOT NULL,
	payload TEXT NOT NULL,
	timestamp INTEGER NOT NULL,
	FOREIGN KEY(fk_server_id)
	REFERENCES Server(id)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Topic (
	id INTEGER NOT NULL PRIMARY KEY,
	fk_server_id INTEGER NOT NULL,
	name TEXT NOT NULL UNIQUE,
	enabled BOOLEAN NOT NULL,
	FOREIGN KEY(fk_server_id)
	REFERENCES Server(id)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Session (
	id INTEGER NOT NULL PRIMARY KEY,
	fk_selected_server_id INTEGER, 
	listen_all_topics BOOLEAN NOT NULL,
	connected BOOLEAN NOT NULL,
	FOREIGN KEY(fk_selected_server_id)
	REFERENCES Server(id)
	ON DELETE CASCADE
);

