import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const geistSans = localFont({
  src: '/fonts/google-font-geist.woff2',
})

const geistMono = localFont({
  src: '/fonts/google-font-geist-mono.woff2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
