name: 'ci'

on:
  push:
    branches:
      - backend
      - frontend

# This workflow will trigger on each push to the `backend` or 'frontned' branch to automatically test, lint and format the code.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/cypress.config.js', '**/cypress.config.ts', '**/cypress.json') }}
          
      - name: install cypress
        run: yarn cypress install

      - name: Cache Cargo dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('./src-tauri/Cargo.lock') }}

      - name: Cache Cargo build artifacts
        uses: actions/cache@v3
        with:
          path: ./src-tauri/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('./src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: run tauri build
        run: yarn tauri build

      - name: Run Cargo tests
        run: cd ./src-tauri && cargo test --release

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev --no-wait
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 # seconds
          browser: edge

      - name: Run Rust lints
        run: cd ./src-tauri && cargo clippy --release -- -D warnings

      - name: Format Rust code
        run: cd ./src-tauri && cargo fmt --all -- --check

      - name: Run ESLint
        run: yarn run lint

      - name: Run Prettier
        run: npx prettier . --check
